services:
  postgres:
    container_name: postgres
    image: postgres:16.8-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nakama"]
      interval: 3s
      timeout: 3s
      retries: 5
  nakama:
    container_name: nakama
    image: echotools/nakama:latest
    env_file:
      - .env
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - /nakama/nakama migrate up && exec /nakama/nakama --config=/data/nakama.yml
   
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis_conf:/usr/local/etc/redis
      - redis_data:/data # Mounts a volume for data persistence
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - backend
volumes:
  data:
  redis_data:
  mongo_data:
networks:
  backend: