package evr

// HAND-CURATED. Nothing generates this file -- edit it by hand, carefully.
//
// There is no generator, no `go:generate` directive, and no committed tool that
// produces this table. It was extracted once, by hand, from a game asset package
// that is not in this repository and cannot be checked in (5.87 GB inflated).
// A "DO NOT EDIT BY HAND" banner previously stood here and was simply false: it
// told the one true maintenance path -- a careful hand edit -- not to happen.
//
// WHAT THIS IS
//
// Cosmetic item id -> the display name the game itself shows the player.
// 624 entries.
//
// WHY IT EXISTS
//
// Aaliyah reported 2026-08-30 that a player's tint would not save. Fixing it by
// hand needs the ID; the game's menu shows only the NAME; and nothing on the
// server mapped between them. The answer was a coin flip, and it was guessed
// wrong once on a real account before this table existed.
//
// WHERE IT CAME FROM, AND WHY EVERY EARLIER SEARCH FAILED
//
//	/mnt/games/cache/ready-at-dawn-echo-arena/_data/5932408047/rad15/win10/
//	  packages/48037dc70b0ecab2_1     Zstandard compressed, 5.87 GB inflated
//
// The names ship with the game, inside zstd-compressed packages. Every plain
// grep over the 4.9 GB install returned nothing -- including a careful bounded
// search with three passing controls -- because grep cannot see into compressed
// data and its silence is indistinguishable from absence.
//
// Layout is [id][marker][display name][category], repeating.
//
// THIS DOES NOT REPLACE THE STRUCT FIELD NAMES in core_account.go.
//
// Those are Andrew's, typed by hand, and several carry knowledge that exists
// nowhere else -- TintBlueSeafoam, TintMesopalgic. "Blue" in those names
// records the ALIGNMENT SLOT, not the colour: TintBlueTerraformed is
// tint_neutral_summer_a_default, whose id says "neutral" and which the server
// nonetheless routes to tint_alignment_a. A display name never carries that
// fact. This table is added ALONGSIDE the field names and overwrites nothing.
//
// (An earlier draft of this header said "Blue" described the colour. That was
// wrong, and the tint-routing bug this file was built for is exactly what it
// got wrong. See alignmentTints in server/evr_profile_cache.go.)
//
// SCOPE, STATED
//
//   - 924 ids were seen in the package; 857 had a display name; 624 survived
//     junk filtering (strings(1) emits fragments like "vvC" and "EV6" that are
//     not names).
//   - 67 ids appear with NO display name in the data at all. They are absent
//     from this map, and CosmeticName reports that as not-found rather than as
//     an empty string -- those are different facts.
//   - One package of four was scanned. This is 624 cosmetics, not provably
//     every cosmetic.
//
// REGENERATE
//
//	zstd -dc <package> | strings -n 3   then pair [id][name] as above.

// cosmeticNames maps a cosmetic item id to its in-game display name.
var cosmeticNames = map[string]string{
	"decal_alien_head_a":              "Alien",
	"decal_anniversary_cupcake_a":     "Happy Cupcake",
	"decal_bear_paw_a":                "Bear Paw",
	"decal_bomb_a":                    "The Bomb",
	"decal_bow_a":                     "Bow",
	"decal_bullseye_a":                "Bullseye",
	"decal_cat_a":                     "Classic Cat",
	"decal_clusters":                  "eyeidx4",
	"decal_combat_anniversary_a":      "1 Year Combat",
	"decal_combat_comet_a":            "Comet",
	"decal_combat_demon_a":            "Lil' Devil",
	"decal_combat_flamingo_a":         "Payload",
	"decal_combat_flying_saucer_a":    "U.F.O.",
	"decal_combat_ice_cream_a":        "Ice Cream",
	"decal_combat_lion_a":             "Lion",
	"decal_combat_logo_a":             "Echo Combat",
	"decal_combat_medic_a":            "Medic!",
	"decal_combat_meteor_a":           "Meteor",
	"decal_combat_military_badge_a":   "Chevron",
	"decal_combat_nova_a":             "Nova",
	"decal_combat_octopus_a":          "Hexapus",
	"decal_combat_pig_a":              "Piglet",
	"decal_combat_pizza_a":            "Pizza",
	"decal_combat_pulsar_a":           "Pulsar",
	"decal_combat_puppy_a":            "Puppy",
	"decal_combat_rage_bear_a":        "Rage Bear",
	"decal_combat_scratch_a":          "Scratch",
	"decal_combat_skull_crossbones_a": "Crossbones",
	"decal_combat_trex_skull_a":       "Fossil",
	"decal_crosshair_a":               "Crosshair",
	"decal_crown_a":                   "Crown",
	"decal_cupcake_a":                 "Cupcake",
	"decal_default":                   "None",
	"decal_dinosaur_a":                "Classic Rex",
	"decal_disc_a":                    "Arena Disc",
	"decal_eagle_a":                   "Eagle",
	"decal_fangs_a":                   "Vampire",
	"decal_fireball_a":                "Fireball",
	"decal_gingerbread_a":             "Gingerbread",
	"decal_halloween_bat_a":           "Spooky Bat",
	"decal_halloween_cat_a":           "Spooky Cat",
	"decal_halloween_cauldron_a":      "Cauldron",
	"decal_halloween_ghost_a":         "Ghost",
	"decal_halloween_pumpkin_a":       "Pumpkin",
	"decal_halloween_scythe_a":        "Scythe",
	"decal_halloween_skull_a":         "Spooky Skull",
	"decal_halloween_zombie_a":        "Zombie",
	"decal_hamburger_a":               "Hamburger",
	"decal_koi_fish_a":                "Koi Fish",
	"decal_kronos_a":                  "Kronos",
	"decal_lightning_bolt_a":          "Lightning",
	"decal_music_note_a":              "Musical",
	"decal_oculus_a":                  "Oculus",
	"decal_one_year_a":                "1 Year",
	"decal_penguin_a":                 "Penguin",
	"decal_present_a":                 "Present",
	"decal_profile_wolf_a":            "Classic Wolf",
	"decal_quest_launch_a":            "Quest",
	"decal_radioactive_a":             "Radioactive",
	"decal_radioactive_bio_a":         "Biohazard",
	"decal_rage_wolf_a":               "Rage Wolf",
	"decal_ray_gun_a":                 "Blaster",
	"decal_rocket_a":                  "Rocket",
	"decal_rose_a":                    "Rose",
	"decal_salt_shaker_a":             "Salty",
	"decal_santa_cubesat_a":           "Holiday Cubesat",
	"decal_saturn_a":                  "Saturn",
	"decal_sheldon_a":                 "Sheldon",
	"decal_skull_a":                   "Flamey Skull",
	"decal_snowflake_a":               "Snowflake",
	"decal_snowman_a":                 "Snowman",
	"decal_spider_a":                  "Spider",
	"decal_summer_pirate_a":           "Pirate",
	"decal_summer_submarine_a":        "Submarine",
	"decal_summer_whale_a":            "Whale",
	"decal_swords_a":                  "Swords",
	"decal_vrml_a":                    "VRML",
	"decal_wreath_a":                  "Wreath",
	"emote_angry_face_a":              "Grumpy",
	"emote_bats_a":                    "Spooky Bats",
	"emote_blink_smiley_a":            "Smiley",
	"emote_broken_heart_a":            "Broken Heart",
	"emote_clock_a":                   "Tick Tock",
	"emote_combat_anniversary_a":      "1 Year Combat",
	"emote_crying_face_a":             "Crying",
	"emote_dancing_octopus_a":         "Dancing Octopus",
	"emote_dead_face_a":               "Dead",
	"emote_deal_glasses_a":            "Sunglasses",
	"emote_default":                   "None",
	"emote_ding":                      "Ding",
	"emote_dizzy_eyes_a":              "Dizzy",
	"emote_dollar_eyes_a":             "Dollar Eyes",
	"emote_exclamation_point_a":       "Exclamation",
	"emote_eye_roll_a":                "Eye Roll",
	"emote_fire_a":                    "Fire",
	"emote_flying_hearts_a":           "Love",
	"emote_func":                      "Bind",
	"emote_gg_a":                      "Good Game",
	"emote_gingerbread_man_a":         "Gingerbread Man",
	"emote_heart_eyes_a":              "Heart Eyes",
	"emote_hourglass_a":               "Hourglass",
	"emote_kissy_lips_a":              "Kissy",
	"emote_lightbulb_a":               "Lightbulb",
	"emote_loading_a":                 "Loading",
	"emote_money_bag_a":               "Money Bag",
	"emote_moustache_a":               "Moustache",
	"emote_pizza_dance":               "Dancing Pizza",
	"emote_present_a":                 "UhJ'",
	"emote_pumpkin_face_a":            "Pumpkin",
	"emote_question_mark_a":           "Confused",
	"emote_reticle_a":                 "Reticle",
	"emote_right_selected":            "self",
	"emote_rip_a":                     "RIP",
	"emote_scared_a":                  "Spooked",
	"emote_shifty_eyes_s2_a":          "Shifty Eyes",
	"emote_sick_face_a":               "Sick",
	"emote_skull_crossbones_a":        "Crossbones",
	"emote_sleepy_zzz_a":              "Sleepy",
	"emote_smirk_face_a":              "Smirk",
	"emote_snow_globe_a":              "Snow Globe",
	"emote_snowman_a":                 "Snowman",
	"emote_spider_a":                  "Spider",
	"emote_star_eyes_a":               "Stars",
	"emote_star_sparkles_a":           "Sparkles",
	"emote_stinky_poop_a":             "Stinky Poop",
	"emote_tabs_reset":                "disabled",
	"emote_tear_drop_a":               "Tear Drop",
	"emote_uwu_s2_a":                  "UwU",
	"emote_vrml_a":                    "VRML",
	"emote_wifi_symbol_a":             "Wifi",
	"emote_winky_tongue_a":            "Tongue",
	"loadout_number":                  "Number",
	"loadout_offset":                  "SinLookup",
	"rwd_banner_0000":                 "Hemisphere",
	"rwd_banner_0002":                 "Swoop",
	"rwd_banner_0003":                 "Amplifier",
	"rwd_banner_0004":                 "Serrated",
	"rwd_banner_0005":                 "Cosmonaut",
	"rwd_banner_0006":                 "Zephyr",
	"rwd_banner_0007":                 "Rime",
	"rwd_banner_0008":                 "Rawhide",
	"rwd_banner_0009":                 "Buzzsaw",
	"rwd_banner_0011":                 "Ragged",
	"rwd_banner_0012":                 "Capacitor",
	"rwd_banner_0013":                 "Drosera",
	"rwd_banner_0014":                 "Crest",
	"rwd_banner_0015":                 "Abyss",
	"rwd_banner_0016":                 "Sunset",
	"rwd_banner_0017":                 "Ribbon",
	"rwd_banner_0018":                 "Lycan",
	"rwd_banner_0019":                 "Keystone",
	"rwd_banner_0020":                 "Pyroclastic",
	"rwd_banner_0021":                 "Gallantry",
	"rwd_banner_0022":                 "Duskblade",
	"rwd_banner_0023":                 "Arisen",
	"rwd_banner_0025":                 "Reaper",
	"rwd_banner_0026":                 "Climber",
	"rwd_banner_0028":                 "Charm",
	"rwd_banner_0029":                 "Ultrafries",
	"rwd_banner_lone_echo_2_a":        "Lone Echo 2",
	"rwd_banner_s1_basic":             "Basic",
	"rwd_banner_s1_bold_stripe":       "Slice",
	"rwd_banner_s1_default":           "Classic",
	"rwd_banner_s1_flames":            "Flame On",
	"rwd_banner_s1_hourglass":         "Hourglass",
	"rwd_banner_s1_squish":            "Regal",
	"rwd_banner_s1_tattered":          "Wartorn",
	"rwd_banner_s2_deco":              "Deco",
	"rwd_banner_s2_ladybug":           "Ladybug",
	"rwd_banner_s2_lines":             "Lines",
	"rwd_banner_s2_pyramids":          "Pyramids",
	"rwd_banner_s2_squares":           "Squares",
	"rwd_banner_sashimono_a":          "Sashimono",
	"rwd_banner_triangles_a":          "Triangles",
	"rwd_booster_anubis_a_horus":      "Horus",
	"rwd_booster_anubis_s2_a":         "Anubis",
	"rwd_booster_aurum_a":             "Aurum",
	"rwd_booster_avian_a":             "Avian",
	"rwd_booster_baroque_a":           "Lustrous",
	"rwd_booster_bee_s2_a":            "Bumblebee",
	"rwd_booster_covenant_a":          "Covenant",
	"rwd_booster_covenant_a_flame":    "Hotrod",
	"rwd_booster_exo_a":               "Sentinel",
	"rwd_booster_flamingo_a":          "Flamingo",
	"rwd_booster_fragment_a":          "Fragment",
	"rwd_booster_fume_a":              "Overdrive",
	"rwd_booster_fume_a_daydream":     "Daydream",
	"rwd_booster_funk_a":              "V-IP",
	"rwd_booster_halloween_a":         "Backbone",
	"rwd_booster_heartbreak_a":        "Heartbreak",
	"rwd_booster_herosuit_a":          "Vega X-3",
	"rwd_booster_junkyard_a":          "Scrapheap",
	"rwd_booster_lava_a":              "Volcanic",
	"rwd_booster_lazurlite_a":         "Lazurite",
	"rwd_booster_mech_a":              "Vanguard",
	"rwd_booster_ninja_a":             "SHIN-0B1",
	"rwd_booster_noble_a":             "Revenant",
	"rwd_booster_nuclear_a":           "Nuclear",
	"rwd_booster_nuclear_a_hydro":     "Hydro",
	"rwd_booster_organic_a":           "Scourge",
	"rwd_booster_overgrown_a":         "Overgrown",
	"rwd_booster_paladin_a":           "Paladin",
	"rwd_booster_plagueknight_a":      "Plague Knight",
	"rwd_booster_ranger_a":            "ranger",
	"rwd_booster_reptile_a":           "Kaiju",
	"rwd_booster_retro_a":             "Rocketeer",
	"rwd_booster_rover_a":             "Rover",
	"rwd_booster_rover_a_deco":        "Spire",
	"rwd_booster_s11_s1_a_fire":       "S11 Flamey",
	"rwd_booster_samurai_a":           "Samurai",
	"rwd_booster_samurai_a_oni":       "Oni",
	"rwd_booster_shark_a":             "Mechalodon",
	"rwd_booster_shark_a_tropical":    "Reefhunter",
	"rwd_booster_snacktime_a":         "Snacktime",
	"rwd_booster_spartan_a":           "Spartan",
	"rwd_booster_spartan_a_hero":      "Hero",
	"rwd_booster_streetwear_a":        "Tempo",
	"rwd_booster_trex_a_skelerex":     "Skelerex",
	"rwd_booster_vintage_a":           "Vintage",
	"rwd_booster_vroom_a":             "Astrodynamic",
	"rwd_booster_wasteland_a":         "Wastelander",
	"rwd_bracer_anubis_a_horus":       "Horus",
	"rwd_bracer_anubis_s2_a":          "Anubis",
	"rwd_bracer_arcade_var_s1_a":      "Golden Age",
	"rwd_bracer_automaton_s2_a":       "Automaton",
	"rwd_bracer_avian_a":              "Avian",
	"rwd_bracer_baroque_a":            "Lustrous",
	"rwd_bracer_bee_s2_a":             "Bumblebee",
	"rwd_bracer_covenant_a":           "Covenant",
	"rwd_bracer_covenant_a_flame":     "Hotrod",
	"rwd_bracer_default":              "None",
	"rwd_bracer_exo_a":                "Sentinel",
	"rwd_bracer_flamingo_a":           "Flamingo",
	"rwd_bracer_fragment_a":           "Fragment",
	"rwd_bracer_fume_a":               "Overdrive",
	"rwd_bracer_fume_a_daydream":      "Daydream",
	"rwd_bracer_halloween_a":          "Backbone",
	"rwd_bracer_heartbreak_a":         "Heartbreak",
	"rwd_bracer_junkyard_a":           "Scrapheap",
	"rwd_bracer_ladybug_s2_a":         "Ladybug",
	"rwd_bracer_lava_a":               "Volcanic",
	"rwd_bracer_lazurlite_a":          "Lazurite",
	"rwd_bracer_mako_s1_a":            "Mako",
	"rwd_bracer_mech_a":               "Vanguard",
	"rwd_bracer_ninja_a":              "SHIN-0B1",
	"rwd_bracer_noble_a":              "Revenant",
	"rwd_bracer_nuclear_a":            "Nuclear",
	"rwd_bracer_nuclear_a_hydro":      "Hydro",
	"rwd_bracer_organic_a":            "Scourge",
	"rwd_bracer_overgrown_a":          "Overgrown",
	"rwd_bracer_paladin_a":            "Paladin",
	"rwd_bracer_plagueknight_a":       "Plague Knight",
	"rwd_bracer_ranger_a":             "ranger",
	"rwd_bracer_reptile_a":            "Kaiju",
	"rwd_bracer_retro_a":              "Rocketeer",
	"rwd_bracer_rover_a":              "Rover",
	"rwd_bracer_rover_a_deco":         "Spire",
	"rwd_bracer_samurai_a":            "Samurai",
	"rwd_bracer_samurai_a_oni":        "Oni",
	"rwd_bracer_scuba_a":              "Aquanaut",
	"rwd_bracer_shark_a":              "Mechalodon",
	"rwd_bracer_shark_a_tropical":     "Reefhunter",
	"rwd_bracer_snacktime_a":          "Snacktime",
	"rwd_bracer_spartan_a":            "Spartan",
	"rwd_bracer_spartan_a_hero":       "Hero",
	"rwd_bracer_streetwear_a":         "Tempo",
	"rwd_bracer_trex_a_skelerex":      "Skelerex",
	"rwd_bracer_trex_s1_a":            "Meteor Rex",
	"rwd_bracer_vintage_a":            "Vintage",
	"rwd_bracer_vroom_a":              "Astrodynamic",
	"rwd_bracer_wasteland_a":          "Wastelander",
	"rwd_bracer_wolf_a":               "Fenrir",
	"rwd_chassis_anubis_a_horus":      "Horus",
	"rwd_chassis_body_s10_a":          "Series-10",
	"rwd_chassis_exo_a":               "Sentinel",
	"rwd_chassis_funk_a":              "V-IP",
	"rwd_chassis_herosuit_a":          "Vega X-3",
	"rwd_chassis_junkyard_a":          "Scrapheap",
	"rwd_chassis_ninja_a":             "SHIN-0B1",
	"rwd_chassis_noble_a":             "Revenant",
	"rwd_chassis_overgrown_a":         "Overgrown",
	"rwd_chassis_plagueknight_a":      "Plague Knight",
	"rwd_chassis_ranger_a":            "ranger",
	"rwd_chassis_samurai_a":           "Samurai",
	"rwd_chassis_samurai_a_oni":       "Oni",
	"rwd_chassis_scuba_a":             "Aquanaut",
	"rwd_chassis_shark_a":             "Mechalodon",
	"rwd_chassis_shark_a_tropical":    "Reefhunter",
	"rwd_chassis_spartan_a":           "Spartan",
	"rwd_chassis_spartan_a_hero":      "Hero",
	"rwd_chassis_sporty_a":            "Comet",
	"rwd_chassis_trex_a_skelerex":     "Skelerex",
	"rwd_chassis_trex_s1_a":           "Meteor Rex",
	"rwd_chassis_wasteland_a":         "Wastelander",
	"rwd_chassis_wolf_a":              "Fenrir",
	"rwd_currency_s01_01":             "This is a short spiel about the item",
	"rwd_currency_s01_02":             "This is a short spiel about the item",
	"rwd_currency_s01_03":             "This is a short spiel about the item",
	"rwd_currency_s01_04":             "This is a short spiel about the item",
	"rwd_currency_s02_01":             "This is a short spiel about the item",
	"rwd_currency_s02_02":             "This is a short spiel about the item",
	"rwd_currency_s02_03":             "This is a short spiel about the item",
	"rwd_currency_s02_04":             "This is a short spiel about the item",
	"rwd_currency_s04_04":             "1Afn",
	"rwd_currency_s05_04":             "1Afn",
	"rwd_currency_s06_04":             "1Afn",
	"rwd_currency_s07_04":             "1Afn",
	"rwd_currency_starter_pack_01":    "This is a short spiel about the item",
	"rwd_decal_0000":                  "Pancakes",
	"rwd_decal_0001":                  "Graffiti",
	"rwd_decal_0002":                  "Mixtape",
	"rwd_decal_0003":                  "Salamander",
	"rwd_decal_0004":                  "Pegasus",
	"rwd_decal_0005":                  "Interceptor",
	"rwd_decal_0006":                  "Gas Mask",
	"rwd_decal_0007":                  "Donut",
	"rwd_decal_0008":                  "Blink",
	"rwd_decal_0009":                  "Incursion",
	"rwd_decal_0010":                  "Hammerhead",
	"rwd_decal_0011":                  "Manta",
	"rwd_decal_0012":                  "Taiyaki",
	"rwd_decal_0013":                  "Rhinestone",
	"rwd_decal_0014":                  "Eruption",
	"rwd_decal_0015":                  "Treant",
	"rwd_decal_0016":                  "Spook",
	"rwd_decal_0018":                  "Physician",
	"rwd_decal_0019":                  "Hoot",
	"rwd_decal_0020":                  "Grim",
	"rwd_decal_0021":                  "Stilt",
	"rwd_decal_0022":                  "Starpower",
	"rwd_decal_axolotl_s2_a":          "Axolotl",
	"rwd_decal_cherry_blossom_a":      "Sakura",
	"rwd_decal_gears_s2_a":            "Gears",
	"rwd_decal_gg_a":                  "Good Game",
	"rwd_decal_narwhal_a":             "Narwhal",
	"rwd_decal_oni_a":                 "Oni",
	"rwd_decal_pepper_a":              "Spicy",
	"rwd_decal_ramen_a":               "Ramen",
	"rwd_decal_scarab_s2_a":           "Scarab",
	"rwd_decal_spartan_a":             "Spartan",
	"rwd_emissive_0001":               "Amber",
	"rwd_emissive_0002":               "Morpho",
	"rwd_emissive_0003":               "Garnet",
	"rwd_emissive_0004":               "Lime",
	"rwd_emissive_0005":               "Ultramarine",
	"rwd_emissive_0006":               "Mesa",
	"rwd_emissive_0007":               "Violet",
	"rwd_emissive_0008":               "Forest",
	"rwd_emissive_0009":               "Lemon",
	"rwd_emissive_0010":               "Seaglass",
	"rwd_emissive_0011":               "Coral",
	"rwd_emissive_0012":               "Wisteria",
	"rwd_emissive_0013":               "Hot and Cold",
	"rwd_emissive_0015":               "This is a short spiel about the item",
	"rwd_emissive_0016":               "Brimstone",
	"rwd_emissive_0017":               "This is a short spiel about the item",
	"rwd_emissive_0018":               "This is a short spiel about the item",
	"rwd_emissive_0019":               "This is a short spiel about the item",
	"rwd_emissive_0022":               "Sunset",
	"rwd_emissive_0023":               "Cotton Candy",
	"rwd_emissive_0024":               "Ghast",
	"rwd_emissive_0025":               "Black and White",
	"rwd_emissive_0026":               "Sanguine",
	"rwd_emissive_0027":               "This is a short spiel about the item",
	"rwd_emissive_0029":               "Nobility",
	"rwd_emissive_0030":               "Verdant",
	"rwd_emissive_0031":               "This is a short spiel about the item",
	"rwd_emissive_0032":               "Hyperlight",
	"rwd_emissive_0033":               "This is a short spiel about the item",
	"rwd_emissive_0035":               "This is a short spiel about the item",
	"rwd_emissive_0037":               "This is a short spiel about the item",
	"rwd_emote_0000":                  "Upside Down",
	"rwd_emote_0001":                  "Equalizer",
	"rwd_emote_0002":                  "High Note",
	"rwd_emote_0003":                  "Get Stomped",
	"rwd_emote_0004":                  "Blast Off",
	"rwd_emote_0005":                  "Burning",
	"rwd_emote_0006":                  "Grimace",
	"rwd_emote_0007":                  "Splat",
	"rwd_emote_0008":                  "Speedometer",
	"rwd_emote_0009":                  "Lock On",
	"rwd_emote_0010":                  "Jelly",
	"rwd_emote_0011":                  "Chomp",
	"rwd_emote_0012":                  "Scuttle",
	"rwd_emote_0013":                  "Shimmer",
	"rwd_emote_0014":                  "Boba",
	"rwd_emote_0017":                  "Boom",
	"rwd_emote_0018":                  "Flex",
	"rwd_emote_0019":                  "Pour",
	"rwd_emote_0020":                  "Fang",
	"rwd_emote_0021":                  "Terror",
	"rwd_emote_0022":                  "Fry Dance",
	"rwd_emote_0023":                  "Confetti",
	"rwd_emote_0024":                  "Quasar",
	"rwd_emote_battery_s1_a":          "Battery",
	"rwd_emote_battle_cry_a":          "Battle Cry",
	"rwd_emote_coffee_s1_a":           "Coffee",
	"rwd_emote_lightning_a":           "Lightning",
	"rwd_emote_meteor_s1_a":           "Meteor",
	"rwd_emote_samurai_mask_a":        "Samurai Mask",
	"rwd_medal_0000":                  "Intro Tier Echo Pass S4",
	"rwd_medal_0001":                  "Mid Tier Echo Pass S4",
	"rwd_medal_0002":                  "Top Tier Echo Pass S4",
	"rwd_medal_0003":                  "Intro Tier Echo Pass S5",
	"rwd_medal_0004":                  "Mid Tier Echo Pass S5",
	"rwd_medal_0005":                  "Top Tier Echo Pass S5",
	"rwd_medal_0007":                  "VRML S4 Finals",
	"rwd_medal_0009":                  "Intro Tier Echo Pass S6",
	"rwd_medal_0010":                  "Mid Tier Echo Pass S6",
	"rwd_medal_0011":                  "Top Tier Echo Pass S6",
	"rwd_medal_0012":                  "Bronze S7",
	"rwd_medal_0013":                  "Silver S7",
	"rwd_medal_0014":                  "Gold S7",
	"rwd_medal_0015":                  "Platinum S7",
	"rwd_medal_0016":                  "Diamond S7",
	"rwd_medal_default":               "None",
	"rwd_medal_lone_echo_2_a":         "Lone Echo 2",
	"rwd_medal_s1_arena_bronze":       "Intro Arena",
	"rwd_medal_s1_arena_gold":         "Top Tier Arena",
	"rwd_medal_s1_combat_bronze":      "Intro Combat",
	"rwd_medal_s1_combat_gold":        "Top Tier Combat",
	"rwd_medal_s1_echo_pass_bronze":   "Intro Echo Pass S1",
	"rwd_medal_s1_echo_pass_gold":     "Top Tier Echo Pass S1",
	"rwd_medal_s1_echo_pass_silver":   "Mid Tier Echo Pass S1",
	"rwd_medal_s1_quest_launch":       "Quest Launch",
	"rwd_medal_s1_vrml_preseason":     "VRML Preseason",
	"rwd_medal_s1_vrml_s1_champion":   "VRML S1 Champ",
	"rwd_medal_s1_vrml_s1_finalist":   "VRML S1 Finals",
	"rwd_medal_s1_vrml_s2_champion":   "VRML S2 Champ",
	"rwd_medal_s1_vrml_s2_finalist":   "VRML S2 Finals",
	"rwd_medal_s1_vrml_s3_champion":   "VRML S3 Champ",
	"rwd_medal_s1_vrml_s3_finalist":   "VRML S3 Finals",
	"rwd_medal_s2_echo_pass_bronze":   "Intro Echo Pass S2",
	"rwd_medal_s2_echo_pass_gold":     "Top Tier Echo Pass S2",
	"rwd_medal_s2_echo_pass_silver":   "Mid Tier Echo Pass S2",
	"rwd_medal_s3_echo_pass_bronze_a": "Intro Tier Echo Pass S3",
	"rwd_medal_s3_echo_pass_gold_a":   "Top Tier Echo Pass S3",
	"rwd_medal_s3_echo_pass_silver_a": "Mid Tier Echo Pass S3",
	"rwd_pip_0001":                    "Hexa",
	"rwd_pip_0002":                    "Atomic",
	"rwd_pip_0003":                    "Botanical",
	"rwd_pip_0004":                    "Pumpkin Patch",
	"rwd_pip_0005":                    "Beveled",
	"rwd_pip_0006":                    "Hotshot",
	"rwd_pip_0007":                    "Intersection",
	"rwd_pip_0009":                    "Pennant",
	"rwd_pip_0010":                    "Fast Track",
	"rwd_pip_0011":                    "Ripped",
	"rwd_pip_0012":                    "Tyrana",
	"rwd_pip_0015":                    "Doppler",
	"rwd_pip_0016":                    "Celestial",
	"rwd_pip_0017":                    "Foamite",
	"rwd_pip_0018":                    "Firework",
	"rwd_pip_0019":                    "Gargoyle",
	"rwd_pip_0020":                    "Sweep",
	"rwd_pip_0021":                    "Target",
	"rwd_pip_0022":                    "Zircon",
	"rwd_pip_0023":                    "Flamboyant",
	"rwd_pip_0024":                    "Rocketship",
	"rwd_pip_0025":                    "Combo",
	"rwd_tag_0000":                    "Ollie",
	"rwd_tag_0001":                    "Fracture",
	"rwd_tag_0003":                    "Downbeat",
	"rwd_tag_0004":                    "Discus",
	"rwd_tag_0006":                    "Soar",
	"rwd_tag_0007":                    "Permafrost",
	"rwd_tag_0009":                    "VRML S4 Finals",
	"rwd_tag_0010":                    "VRML S4 Champ",
	"rwd_tag_0011":                    "Echo VR Game Admin",
	"rwd_tag_0012":                    "Exhaust",
	"rwd_tag_0013":                    "Shiv",
	"rwd_tag_0014":                    "Barbed",
	"rwd_tag_0015":                    "Boost",
	"rwd_tag_0016":                    "Accelerator",
	"rwd_tag_0017":                    "Membrane",
	"rwd_tag_0018":                    "Leviathan",
	"rwd_tag_0019":                    "Hunter",
	"rwd_tag_0020":                    "Ambush",
	"rwd_tag_0021":                    "Swell",
	"rwd_tag_0023":                    "Ornate",
	"rwd_tag_0025":                    "Gardenia",
	"rwd_tag_0026":                    "Divergence",
	"rwd_tag_0027":                    "Mosaic",
	"rwd_tag_0028":                    "Striation",
	"rwd_tag_0029":                    "Banderole",
	"rwd_tag_0030":                    "Bolt",
	"rwd_tag_0031":                    "Tatter",
	"rwd_tag_0033":                    "Liana",
	"rwd_tag_0034":                    "Shuriken",
	"rwd_tag_0036":                    "VRML S5 Finals",
	"rwd_tag_0037":                    "VRML S5 Champ",
	"rwd_tag_0038":                    "Stand",
	"rwd_tag_0039":                    "Liminal",
	"rwd_tag_0041":                    "VRML S6 Finals",
	"rwd_tag_0044":                    "VRML S7 Finals",
	"rwd_tag_0045":                    "VRML S7 Champ",
	"rwd_tag_default":                 "None",
	"rwd_tag_diamonds_a":              "Diamonds",
	"rwd_tag_lone_echo_2_a":           "Lone Echo 2",
	"rwd_tag_s1_c_secondary":          "Slice",
	"rwd_tag_s1_e_secondary":          "Triangle",
	"rwd_tag_s1_g_secondary":          "Flame On",
	"rwd_tag_s1_h_secondary":          "Disc",
	"rwd_tag_s1_j_secondary":          "Stairway",
	"rwd_tag_s1_k_secondary":          "Classic",
	"rwd_tag_s1_m_secondary":          "Arrow",
	"rwd_tag_s1_o_secondary":          "Striped",
	"rwd_tag_s1_q_secondary":          "Hero",
	"rwd_tag_s1_t_secondary":          "Notched",
	"rwd_tag_s1_vrml_preseason":       "VRML Preseason",
	"rwd_tag_s1_vrml_s1_champion":     "VRML S1 Champ",
	"rwd_tag_s1_vrml_s1_finalist":     "VRML S1 Finals",
	"rwd_tag_s1_vrml_s2_champion":     "VRML S2 Champ",
	"rwd_tag_s1_vrml_s2_finalist":     "VRML S2 Finals",
	"rwd_tag_s1_vrml_s3_champion":     "VRML S3 Champ",
	"rwd_tag_s1_vrml_s3_finalist":     "VRML S3 Finals",
	"rwd_tag_s2_b_secondary":          "Rectilinear",
	"rwd_tag_s2_c":                    "Nimbus",
	"rwd_tag_s2_g_secondary":          "Clockwork",
	"rwd_tag_s2_h_secondary":          "Serpent",
	"rwd_tag_spear_a":                 "Spear",
	"rwd_tag_tori_a":                  "Tori",
	"rwd_tint_0000":                   "Bubblemint",
	"rwd_tint_0001":                   "Swiss",
	"rwd_tint_0002":                   "Lilac",
	"rwd_tint_0003":                   "Prime",
	"rwd_tint_0004":                   "Moonwalker",
	"rwd_tint_0005":                   "Flaxen",
	"rwd_tint_0006":                   "Reptilian",
	"rwd_tint_0007":                   "Marimo",
	"rwd_tint_0008":                   "Oxidation",
	"rwd_tint_0009":                   "Badlands",
	"rwd_tint_0010":                   "Ignition",
	"rwd_tint_0011":                   "Fuse",
	"rwd_tint_0012":                   "Amalgam",
	"rwd_tint_0013":                   "Algae",
	"rwd_tint_0014":                   "Coastline",
	"rwd_tint_0015":                   "Mesopelagic",
	"rwd_tint_0016":                   "Drizzle",
	"rwd_tint_0017":                   "Molten",
	"rwd_tint_0018":                   "Chic",
	"rwd_tint_0019":                   "Mesopelagic",
	"rwd_tint_0020":                   "Eminence",
	"rwd_tint_0021":                   "Ectoplasm",
	"rwd_tint_0022":                   "Chlorophyll",
	"rwd_tint_0023":                   "Urban",
	"rwd_tint_0024":                   "Bubble Pop",
	"rwd_tint_0025":                   "Velvet",
	"rwd_tint_0028":                   "Weathered",
	"rwd_tint_0029":                   "Jasper",
	"rwd_tint_s1_a_default":           "Morning Glory",
	"rwd_tint_s1_b_default":           "Seafoam",
	"rwd_tint_s1_c_default":           "Burnt Embers",
	"rwd_tint_s1_d_default":           "Luminescence",
	"rwd_tint_s2_a_default":           "Stereoscopic",
	"rwd_tint_s2_b_default":           "Patina",
	"rwd_tint_s2_c_default":           "Desert Jewel",
	"rwd_tint_s3_tint_a":              "Frostflame",
	"rwd_tint_s3_tint_b":              "Bloodstained",
	"rwd_tint_s3_tint_c":              "Biohazard",
	"rwd_tint_s3_tint_d":              "Mixed Berry",
	"rwd_tint_s3_tint_e":              "Tranquility",
	"rwd_title_0000":                  "Rider of Rhythm",
	"rwd_title_0001":                  "Street Artist",
	"rwd_title_0003":                  "Shooting Star",
	"rwd_title_0004":                  "Scrapper",
	"rwd_title_0005":                  "Arena Outcast",
	"rwd_title_0006":                  "Atomic Powerhouse",
	"rwd_title_0007":                  "Changer of Tides",
	"rwd_title_0008":                  "Deep Dive Striker",
	"rwd_title_0009":                  "Free Floater",
	"rwd_title_0010":                  "Ghastly Esquire",
	"rwd_title_0011":                  "Eldritch Eye",
	"rwd_title_0012":                  "Knightmare",
	"rwd_title_0013":                  "Master Passer",
	"rwd_title_0014":                  "The Valiant",
	"rwd_title_0015":                  "The Invincible",
	"rwd_title_0016":                  "Steadfast",
	"rwd_title_0017":                  "Noble",
	"rwd_title_0018":                  "Loyalist",
	"rwd_title_0019":                  "The Lifer",
	"rwd_title_guardian_a":            "The Guardian",
	"rwd_title_ronin_a":               "Ronin",
	"rwd_title_s1_a":                  "Mechasaur",
	"rwd_title_s1_b":                  "Oops! I Dinged It Again",
	"rwd_title_s1_c":                  "Super Nova",
	"rwd_title_s2_a":                  "The Wall",
	"rwd_title_s2_b":                  "Tipper of Scales",
	"rwd_title_s2_c":                  "Recycled Goods",
	"rwd_title_shield_bearer_a":       "Shield Bearer",
	"rwd_title_title_a":               "Dunk Master",
	"rwd_title_title_b":               "Flamingo Tamer",
	"rwd_title_title_default":         "None",
	"rwd_title_title_e":               "Fists of Fury",
	"rwd_xp_boost_individual_s01_01":  "This is a short spiel about the item",
	"rwd_xp_boost_individual_s01_02":  "This is a short spiel about the item",
	"rwd_xp_boost_individual_s01_03":  "This is a short spiel about the item",
	"rwd_xp_boost_individual_s01_04":  "This is a short spiel about the item",
	"rwd_xp_boost_individual_s01_05":  "This is a short spiel about the item",
	"rwd_xp_boost_individual_s02_01":  "This is a short spiel about the item",
	"rwd_xp_boost_individual_s02_02":  "This is a short spiel about the item",
	"rwd_xp_boost_individual_s02_03":  "This is a short spiel about the item",
	"rwd_xp_boost_individual_s02_04":  "This is a short spiel about the item",
	"rwd_xp_boost_individual_s02_05":  "This is a short spiel about the item",
	"rwd_xp_boost_individual_s03_01":  "1Afn",
	"rwd_xp_boost_individual_s03_02":  "1Afn",
	"rwd_xp_boost_individual_s03_03":  "1Afn",
	"rwd_xp_boost_individual_s03_04":  "1Afn",
	"rwd_xp_boost_individual_s04_01":  "1Afn",
	"rwd_xp_boost_individual_s04_02":  "1Afn",
	"rwd_xp_boost_individual_s04_03":  "1Afn",
	"rwd_xp_boost_individual_s04_04":  "1Afn",
	"rwd_xp_boost_individual_s05_01":  "1Afn",
	"rwd_xp_boost_individual_s05_02":  "1Afn",
	"rwd_xp_boost_individual_s05_03":  "1Afn",
	"rwd_xp_boost_individual_s05_04":  "1Afn",
	"rwd_xp_boost_individual_s06_01":  "1Afn",
	"rwd_xp_boost_individual_s06_02":  "1Afn",
	"rwd_xp_boost_individual_s06_03":  "1Afn",
	"rwd_xp_boost_individual_s06_04":  "1Afn",
	"rwd_xp_boost_individual_s07_01":  "1Afn",
	"rwd_xp_boost_individual_s07_02":  "1Afn",
	"rwd_xp_boost_individual_s07_03":  "1Afn",
	"rwd_xp_boost_individual_s07_04":  "1Afn",
}

// TintAlignment records which alignment slot a tint belongs to, for tints where
// the id does not say.
//
// SUPERSEDABLE -- READ THIS BEFORE EXTENDING IT BY HAND.
//
// The game declares slot semantics itself, in plain JSON, no decompression:
//
//	sourcedb/rad15/json/r14/multiplayer/equip_slots.json   (1589 bytes)
//	  {"equipslot":"tint"}                                  no alignment key
//	  {"equipslot":"tint_alignment_a","alignmentrequirement":0}   BLUE
//	  {"equipslot":"tint_alignment_b","alignmentrequirement":1}   ORANGE
//	  {"equipslot":"tint_body","alignmentrequirement":-1}          none
//
// So the SLOTS and their alignment requirements are authoritative there, and
// this hand-built map should be replaced by reading that file rather than
// extended. It exists because it was written before the file was found.
//
// Found by Teth, 2026-08-31, in the install all three of us had searched.
//
// It also settles a question I had asked a person instead: tint and tint_body
// are INDEPENDENTLY DECLARED slots. They both held tint_neutral_l_default
// because that is the default, not because they are coupled.
//
// # WHY THIS IS SEPARATE FROM cosmeticNames
//
// The game's display string is a LABEL and carries no slot information --
// "Luminescence" does not tell you it lives under the BLUE tab. Andrew's struct
// field names in core_account.go DO: TintBlueLuminescence on an rwd_tint_s1_*
// id is the only record anywhere that this is an alignment tint rather than a
// social one.
//
// That distinction is load-bearing. On 2026-08-31 a player could not equip
// Luminescence because the game routes an alignment tint to the alignment slot,
// while the remotelog-based cosmetic extraction reports only THAT an item was
// set and never WHICH SLOT -- so the server guessed, and guessed the social
// slot. Setting cosmetic_loadout.tint did nothing; tint_alignment_a was the
// answer.
//
// These three are the complete set whose slot is recorded nowhere but in a
// hand-typed identifier. Extracting display names would have silently lost it.
//
// Andrew, 2026-08-31: slot handling is done correctly in nevr-server-rs and the
// new nevr-runtime DLLs, so this is expected to become unnecessary. Recorded
// until it is.
var tintAlignment = map[string]string{
	"rwd_tint_s1_b_default":         "blue", // Seafoam
	"rwd_tint_s1_d_default":         "blue", // Luminescence
	"tint_neutral_summer_a_default": "blue", // Terraformed -- no game string at all
}

// TintAlignmentSlot reports the alignment slot for a tint id, if known.
// Not-found means "we have no record", NOT "it is a social tint".
func TintAlignmentSlot(id string) (string, bool) {
	s, ok := tintAlignment[id]
	return s, ok
}

// CosmeticName returns the in-game display name for a cosmetic id.
//
// The second return value distinguishes "this id has no name in the shipped
// data" from "this id is unknown to us" only insofar as both are false; callers
// that need the difference should consult the SCOPE note above. It is
// deliberately not an empty-string sentinel: a missing name and a blank name
// must not look alike.
func CosmeticName(id string) (string, bool) {
	n, ok := cosmeticNames[id]
	return n, ok
}

// CosmeticID returns the first cosmetic id whose display name matches exactly.
// Names are not guaranteed unique; callers wanting all matches should range
// over CosmeticNames themselves.
func CosmeticID(displayName string) (string, bool) {
	for id, n := range cosmeticNames {
		if n == displayName {
			return id, true
		}
	}
	return "", false
}

// CosmeticNames exposes a copy of the table for callers that need to iterate.
func CosmeticNames() map[string]string {
	out := make(map[string]string, len(cosmeticNames))
	for k, v := range cosmeticNames {
		out[k] = v
	}
	return out
}
